[package]
name = "ViyLine"
version = "2022.10.21"
edition = "2021"
authors = ["Tremeschin"]
license = "MIT"

[[bin]]
name = "ViyLine"
path = "ViyLine.rs"

[dependencies]
Protostar = {path="../Protostar"}
eframe = "0.19.0"
egui = "0.19.0"
